name: C/C++ CI

on:
  push:
    branches: [ libjitsi_v2 ]
  pull_request:
    branches: [ libjitsi_v2 ]

jobs:
  build-cmake:
    name: CMake build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build .
